const text = ['Aliquam convallis sagittis lorem, id interdum arcu elementum nec. Etiam lacinia commodo sem sit amet laoreet. Sed sed ultrices felis. Cras suscipit luctus magna eget volutpat. Donec sagittis est at lorem hendrerit ultricies. Ut dapibus mauris sed libero lobortis facilisis. Ut gravida ut elit sed facilisis. Quisque luctus ullamcorper velit, id ultrices augue. Duis dignissim eros nec mollis aliquam. Suspendisse finibus velit sed lacus tincidunt vehicula at sit amet elit.',

'Donec metus mi, pharetra ac arcu euismod, euismod suscipit leo. Nunc tempor, nisl eu interdum eleifend, metus quam luctus purus, finibus eleifend tellus purus in orci. Cras ac finibus nulla, sed aliquam lacus. Cras auctor tellus vel nunc elementum facilisis. Curabitur aliquam mi eget nisl ornare rutrum. Suspendisse potenti. Duis nec ipsum quam. Nunc nisl lectus, vestibulum nec aliquam sed, eleifend in ex. Morbi id dui quis nisl volutpat aliquet. Nulla eleifend tortor in nunc eleifend suscipit. Sed vitae metus eu tellus dapibus congue.',

'Morbi non nulla eget sapien hendrerit vestibulum. Maecenas pellentesque at magna ac volutpat. Duis risus nunc, facilisis porttitor tincidunt convallis, vulputate id quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pharetra dignissim ligula, ut faucibus ipsum ultricies id. Nam interdum id enim et consequat. Morbi non ultricies ipsum, in blandit metus. Fusce iaculis urna purus, eget pellentesque justo dictum eget. Aliquam erat volutpat.',

'Sed lorem neque, viverra ut lacus eget, congue sollicitudin nisi. Donec ac egestas ante, a elementum ante. Proin rutrum euismod sodales. Suspendisse eros lectus, sagittis non bibendum id, feugiat in dolor. Donec mollis nisi eget placerat fringilla. Mauris ex magna, hendrerit sed mattis vel, porttitor in lorem. Sed vel erat facilisis, congue risus ut, lacinia massa. Aenean vehicula ultricies urna, sit amet imperdiet eros tempus non. Praesent consectetur dui ut ante vestibulum, ut viverra ipsum aliquet. Nullam leo nisl, gravida sed efficitur sed, cursus vel risus. Sed ac laoreet lacus, eu lobortis nulla. Nullam sed ornare nibh.',

'Duis tempor imperdiet eros porttitor sagittis. Mauris sagittis nisl in magna bibendum pharetra. Nullam vel hendrerit sapien. Donec fermentum blandit tellus, in elementum magna efficitur nec. Integer porta, libero in finibus viverra, ligula diam accumsan nisi, a auctor eros dolor vel est. Donec id ipsum eu orci ultricies congue vitae nec dolor. Aliquam ultricies scelerisque est, sed pretium odio tristique quis. Nulla eu dolor et justo mollis molestie. Nam id metus vel lectus malesuada tempor.',

'Nam non accumsan dui. Nulla quis urna nec arcu egestas vulputate. Donec dignissim, nibh eget malesuada vulputate, nulla diam volutpat nisl, eget fermentum mi leo sed nunc. Aenean vitae arcu euismod, tincidunt nulla vitae, ultricies eros. Vestibulum non libero id massa blandit egestas vel vehicula dui. Pellentesque porttitor elit a enim viverra, ut iaculis nibh fermentum. Aenean mattis, elit sit amet molestie congue, arcu leo faucibus lectus, id egestas nibh tortor in augue. Nullam elit turpis, mattis sit amet aliquet vehicula, feugiat quis purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi in ultrices lorem, at vestibulum odio. Mauris cursus congue nisi nec condimentum.',

'Nulla convallis sed magna ut lobortis. Etiam tempor justo sit amet mi viverra interdum. Nullam fringilla consequat urna, quis porttitor ipsum efficitur id. Donec facilisis volutpat sem, nec pretium orci lobortis ut. Ut quis tincidunt odio. Duis id malesuada justo, at maximus ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.'];

export default text;
