const text = ['Integer eleifend vehicula nisi, commodo volutpat erat vestibulum nec. Donec efficitur odio id ligula luctus pretium. Nulla malesuada lacinia felis ut faucibus. Maecenas ac sem ac est elementum elementum. Mauris congue varius sollicitudin. Proin nec sollicitudin quam. Donec ullamcorper mauris non urna vehicula sollicitudin. Cras ante arcu, hendrerit vitae vulputate eu, interdum nec lorem. Duis vitae odio velit. Sed tempus auctor sollicitudin. Sed massa dolor, tristique ac elit vitae, auctor convallis lectus. Sed nec felis neque. Nullam scelerisque facilisis tellus eget efficitur. Phasellus metus sem, suscipit quis commodo a, suscipit vel orci.',

'Quisque at tellus pulvinar neque ornare vehicula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum bibendum ornare quam, a rhoncus mauris faucibus at. Aliquam tempor mattis dui nec congue. Pellentesque libero ipsum, volutpat eget gravida eget, vehicula nec ipsum. Quisque id accumsan velit. Ut cursus ipsum at massa consectetur, quis pulvinar arcu semper. Nam ullamcorper nulla eu orci porttitor, a ullamcorper tortor lacinia. Sed at feugiat nisl. Sed luctus, nulla ac laoreet lacinia, tellus ante cursus augue, tristique luctus dui orci venenatis tellus. Suspendisse quis tincidunt nibh. Mauris accumsan leo a neque iaculis, sit amet posuere nunc dignissim. Nunc elementum eu velit non commodo.',

'Nunc in imperdiet arcu. Nulla facilisi. Sed nisi nisi, finibus aliquam lorem et, malesuada rutrum enim. Vivamus aliquam non nisi sit amet vestibulum. Nam a lacus odio. Sed orci mi, finibus quis augue non, ultricies auctor nulla. Vestibulum ornare pretium magna, ut efficitur quam tempus non. In id venenatis sapien, nec vestibulum nunc. Nulla vel odio sit amet ipsum volutpat tempus. Vivamus eros risus, pellentesque vel felis in, iaculis tempus odio. In in molestie risus.',

'Curabitur pulvinar sit amet odio eget iaculis. Suspendisse maximus porta ex eget porta. Curabitur neque est, sollicitudin vel erat at, commodo pulvinar ipsum. Pellentesque commodo tristique urna, eu blandit dui cursus vulputate. Suspendisse placerat varius massa, eu ornare mi mollis nec. Praesent orci ante, dictum vitae tempus quis, sagittis quis nibh. In faucibus luctus metus, ac varius neque rutrum vitae. Vivamus pretium, tortor tempus semper imperdiet, quam purus ullamcorper orci, sit amet egestas magna nulla at lacus. Duis vitae lectus eget sem porta vestibulum vel sit amet elit. Donec at turpis vel justo tempus gravida vel ac purus. Vestibulum nec mauris non ligula sollicitudin commodo. Donec suscipit velit eu nisi porta rhoncus. Curabitur facilisis ultrices sapien, eu ullamcorper ligula efficitur nec. Ut tincidunt in orci ut porttitor. Donec ut orci nibh.'];

export default text;
